import * as Interfaces from '../interface_tests';
export declare const createBlog: (blog: Interfaces.Blog) => string;
export declare const patchBlog: (id: string, blog: Interfaces.Blog) => string;
export declare const showBlog: (id: string, grabBlog: any) => void;
export declare const destroyBlog: (id: string) => void;
export declare const getAllBlogs: (updateBlogsList: any) => void;
export declare const createProject: (project: Interfaces.Project) => string;
export declare const patchProject: (id: string, project: Interfaces.Project) => string;
export declare const showProject: (id: string, grabProject: any) => void;
export declare const destroyProject: (id: string) => void;
export declare const getAllProjects: (updateProjectsList: any) => void;
export declare const getTopProjects: (updateProjectsList: any) => void;
export declare const createContact: (contact: Interfaces.Contact) => string;
export declare const destroyContact: (id: string) => void;
export declare const getAllContacts: (updateContactsList: any) => void;
